#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jun 14, 2021 12:01:17 AM CST  platform: Windows NT
# 部分用于支撑gui的函数（以及报告保存函数）（混入了奇怪的东西）


import sys

import pandas as pd

import tkinter as tk
import tkinter.ttk as ttk

from tksheet import Sheet


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    

def saveMd(contain,sheetContain,analySheet,img1Contain,img2Contain):
    print('gui_support.saveMd')
    sys.stdout.flush()
    output = contain + sheetContain + analySheet +'## 数据可视化\n'+ img1Contain + img2Contain
    with open('Report.md', 'w', encoding='utf-8') as file:
        file.write(output)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()

